import { useState } from "react";
import { Card, EmptyState, Icon, Pill, SegmentedButton } from "../components";
import type { ApplyData, CockpitData, PolicyData, StateData } from "../types";
import { pct, time, titleCase } from "../format";

type DiagTab = "state" | "policy" | "apply" | "bindings" | "logs" | "raw";

export function DiagnosticsPage({ data }: { data: CockpitData }) {
  const [tab, setTab] = useState<DiagTab>("state"); const state: StateData = data.state?.data || {}; const policy: PolicyData = data.policy?.data || {}; const apply: ApplyData = data.apply?.data || {}; const diagnostics = data.diagnostics?.data || {};
  const tabs: Array<[DiagTab, string]> = [["state", "Zustand"], ["policy", "Entscheidung"], ["apply", "Apply & Queue"], ["bindings", "Bindings"], ["logs", "Logs"], ["raw", "Raw JSON"]];
  return <div className="diagnostics-page"><div className="diag-tabs">{tabs.map(([id, label]) => <SegmentedButton key={id} active={tab === id} onClick={() => setTab(id)}>{label}</SegmentedButton>)}</div>
    {tab === "state" && <div className="diag-grid"><Card title="Zustandserkennung"><KeyValues data={{ Szenario: state.context || state.media_scenario, Subkontext: state.subcontext, Gerät: state.device, "Gaming-Quelle": state.gaming_source, Plattform: state.gaming_platform, "Entertainment aktiv": state.entertainment_active, "Headset aktiv": state.headset_active }} /></Card><Card title="Core-State-Kontext"><KeyValues data={state.context_cards || {}} /></Card><Card title="Aktive Gründe"><List values={state.active_reasons || []} /></Card><Card title="Classifier"><KeyValues data={Object.fromEntries(Object.entries(state.classifiers || {}).map(([key, value]) => [key, `${value.enum ?? "—"} · ${value.label || "—"}`]))} /></Card></div>}
    {tab === "policy" && <div className="diag-grid"><Card title="Decision Engine"><KeyValues data={{ "Audio Owner": policy.audio_owner, Szenario: policy.audio_scenario_label, Detail: policy.audio_scenario_detail, Aktion: policy.action, "Volume Policy": policy.volume_policy, HomePods: pct(policy.volume_target_homepods), Denon: pct(policy.volume_target_denon), "Subwoofer erlaubt": policy.subwoofer_allowed }} /></Card><Card title="Why-Stack"><div className="diag-list">{(policy.reasons || []).map((reason, index) => <div key={index}><Pill tone={reason.severity === "warn" ? "orange" : "green"}>{reason.severity || "ok"}</Pill><span>{reason.text}</span></div>)}</div></Card><Card title="Nudge / Boost"><KeyValues data={policy.nudge || {}} /></Card><Card title="Volume-Formel"><pre>{JSON.stringify(policy.volume_formula || {}, null, 2)}</pre></Card></div>}
    {tab === "apply" && <div className="diag-grid"><Card title="Gate"><KeyValues data={apply.gates || {}} /></Card><Card title="Queue / Debounce"><KeyValues data={apply.debounce || {}} /></Card><Card title="Nächster Plan"><KeyValues data={apply.plan || {}} /></Card><Card title="Nachlauf"><KeyValues data={apply.nachlauf || {}} /></Card></div>}
    {tab === "bindings" && <div className="binding-grid">{Object.entries(diagnostics.bindings || {}).map(([module, bindings]: [string, any]) => <Card title={`Bindings · ${titleCase(module)}`} key={module}><div className="bindings">{bindings.map((binding: any) => <div key={binding.key}><span>{binding.key}<small>{binding.entity_id || "nicht gebunden"}</small></span><Pill tone={binding.status === "bound" ? "green" : binding.status === "unavailable" ? "orange" : "neutral"}>{binding.status}</Pill></div>)}</div></Card>)}{!Object.keys(diagnostics.bindings || {}).length && <Card><EmptyState title="Keine Binding-Daten" text="Diagnostics liefert derzeit keine Bindings." /></Card>}</div>}
    {tab === "logs" && <Card title="Apply-Log"><div className="action-log technical">{(apply.log || []).map((entry, index) => <div key={index}><time>{time(entry.ts)}</time><Icon.Activity size={16} /><span>{entry.action || "—"} · HP {pct(entry.homepods_target)} · Denon {pct(entry.denon_target)}</span><Pill tone={entry.executed ? "green" : "orange"}>{entry.executed ? "live" : "shadow"}</Pill></div>)}</div></Card>}
    {tab === "raw" && <Card title="Raw JSON" action={<button className="button" onClick={() => void navigator.clipboard?.writeText(JSON.stringify({ state, policy, apply, diagnostics }, null, 2))}>JSON kopieren</button>}><pre className="raw-json">{JSON.stringify({ state, policy, apply, diagnostics }, null, 2)}</pre></Card>}
  </div>;
}

function KeyValues({ data }: { data: Record<string, any> }) { const entries = Object.entries(data).filter(([, value]) => value !== undefined); return entries.length ? <div className="key-values">{entries.map(([key, value]) => <span key={key}>{titleCase(key)}<b>{typeof value === "object" ? JSON.stringify(value) : typeof value === "boolean" ? value ? "Ja" : "Nein" : String(value ?? "—")}</b></span>)}</div> : <EmptyState compact title="Keine Daten" text="Dieser Snapshot-Bereich ist leer." />; }
function List({ values }: { values: string[] }) { return values.length ? <div className="diag-list">{values.map((value) => <div key={value}><Icon.ChevronRight size={16} /><span>{value}</span></div>)}</div> : <EmptyState compact title="Keine Einträge" text="Aktuell sind keine Gründe aktiv." />; }
