import { useMemo, useState } from "react";
import { Card, EmptyState, Icon, Pill, SegmentedButton } from "../components";
import { resetMatrix, setMatrix, setScalars } from "../api";
import type { ApplyData, HassLike, MatrixData } from "../types";
import { titleCase } from "../format";

const labels: Record<string, string> = { early_morning: "Früher Morgen", late_morning: "Später Morgen", forenoon: "Vormittag", afternoon: "Nachmittag", early_evening: "Früher Abend", late_evening: "Später Abend", early_night: "Frühe Nacht", late_night: "Späte Nacht", homepods: "HomePods", denon: "Denon", private_denon_cap: "Private-Time-Cap", boost_offset: "Track-Boost", grind_homepods_offset: "Grind-Offset", grind_denon_offset: "Grind-Offset", opening_offset_homepods: "Fenster-Offset", opening_offset_denon: "Fenster-Offset", homepods_max: "Maximalpegel", denon_max: "Maximalpegel", ducked_target: "Quiet-Mode-Ziel", active_min: "Aktiv-Mindestpegel" };
type Dimension = "base" | "scenario_off" | "activity_off";

function PercentInput({ value, overridden, onSave }: { value?: number; overridden?: boolean; onSave: (value: number) => void }) {
  const [draft, setDraft] = useState(String(Math.round(Number(value || 0) * 100)));
  return <label className={`percent-input ${overridden ? "overridden" : ""}`}><input type="number" value={draft} min={-100} max={100} onChange={(e) => setDraft(e.target.value)} onBlur={() => onSave(Number(draft) / 100)} onKeyDown={(e) => e.key === "Enter" && onSave(Number(draft) / 100)} /><span>%</span></label>;
}

export function RulesPage({ matrix, apply = {}, hass, onMatrix }: { matrix?: MatrixData; apply?: ApplyData; hass: HassLike; onMatrix: (matrix: MatrixData) => void }) {
  const [tab, setTab] = useState<"matrix" | "safety" | "delays">("matrix"); const [busy, setBusy] = useState(false);
  const saveCell = async (dim: Dimension, device: string, key: string, value: number) => { setBusy(true); try { onMatrix(await setMatrix(hass, { [dim]: { [device]: { [key]: value } } })); } finally { setBusy(false); } };
  const saveScalar = async (key: string, value: number) => { setBusy(true); try { onMatrix(await setScalars(hass, { [key]: value })); } finally { setBusy(false); } };
  const dimensions = useMemo(() => matrix ? [{ key: "base" as Dimension, title: "Tagesphasen-Basis", sub: "Grundlautstärke pro Tagesphase", rows: matrix.catalog.dayphases }, { key: "scenario_off" as Dimension, title: "Szenario-Offsets", sub: "Additiver Offset pro Szenario", rows: matrix.catalog.scenarios }, { key: "activity_off" as Dimension, title: "Activity-Offsets", sub: "Additiver Offset pro Aktivität", rows: matrix.catalog.activities }] : [], [matrix]);
  if (!matrix) return <Card><EmptyState icon={Icon.SlidersHorizontal} title="Regel-Contract nicht verfügbar" text="benni_media_policy/get_matrix konnte nicht geladen werden. Es wird nichts lokal gespeichert." /></Card>;
  const scalarGroups = [{ title: "HomePods", device: "homepods", keys: ["opening_offset_homepods", "grind_homepods_offset", "homepods_max", "boost_offset", "active_min"] }, { title: "Denon", device: "denon", keys: ["opening_offset_denon", "grind_denon_offset", "denon_max", "private_denon_cap", "active_min"] }];
  return <div className={`rules-page ${busy ? "busy" : ""}`}><div className="rules-tabs"><SegmentedButton active={tab === "matrix"} onClick={() => setTab("matrix")} icon={Icon.SlidersHorizontal}>Matrix</SegmentedButton><SegmentedButton active={tab === "safety"} onClick={() => setTab("safety")} icon={Icon.ShieldCheck}>Caps & Modi</SegmentedButton><SegmentedButton active={tab === "delays"} onClick={() => setTab("delays")} icon={Icon.Activity}>Delays & Sleep</SegmentedButton><span /><button className="button danger" onClick={async () => { if (!window.confirm("Alle Matrix-Overrides auf Defaults zurücksetzen?")) return; onMatrix(await resetMatrix(hass)); }}><Icon.RefreshCw size={17} />Matrix zurücksetzen</button></div>
    {tab === "matrix" && <>{dimensions.map((dimension, index) => <Card className="rule-section" key={dimension.key}><div className="rule-title"><span>{index + 1}</span><div><h2>{dimension.title}</h2><p>{dimension.sub}</p></div><div className="rule-device-head"><b>HomePods</b><b>Denon</b></div></div><div className="rule-table">{dimension.rows.map((row) => <div className="rule-row" key={row}><span>{labels[row] || matrix.catalog.scenario_labels[row] || titleCase(row)}</span>{["homepods", "denon"].map((device) => <PercentInput key={device} value={matrix[dimension.key]?.[device]?.[row]} overridden={matrix.override?.[dimension.key]?.[device]?.[row] !== undefined} onSave={(value) => void saveCell(dimension.key, device, row, value)} />)}</div>)}</div></Card>)}</>}
    {tab === "safety" && <div className="scalar-grid">{scalarGroups.map((group) => <Card title={group.title} key={group.title} action={<Pill tone={group.device === "homepods" ? "pink" : "cyan"}>getrennt</Pill>}><div className="scalar-list">{group.keys.map((key) => <div key={key}><span>{labels[key] || titleCase(key)}</span><PercentInput value={matrix.scalars[key]} onSave={(value) => void saveScalar(key, value)} /></div>)}</div></Card>)}<Card title="Nicht doppelt konfiguriert"><p className="muted-copy">Alle Änderungen schreiben über <code>set_scalars</code> in dieselben ConfigEntry-Options wie der Backend-Options-Flow. Matrixwerte landen im bestehenden Policy-Store.</p></Card></div>}
    {tab === "delays" && <div className="scalar-grid"><Card title="Apply & Queue"><div className="key-values"><span>Debounce<b>{apply.settings?.debounce_seconds ?? "—"} s</b></span><span>Ramp-Schritte<b>{apply.settings?.ramp_steps ?? "—"}</b></span><span>Ramp-Delay<b>{apply.settings?.ramp_step_delay_s ?? "—"} s</b></span><span>Tiny Delta<b>{apply.settings?.tiny_delta ?? "—"}</b></span></div></Card><Card title="Sleep & Wake"><div className="key-values"><span>Sleep-TV-Delay<b>{apply.sleep_tv?.delay_s ?? "—"} s</b></span><span>Warn-Vorlauf<b>{apply.sleep_tv?.warn_lead_s ?? "—"} s</b></span><span>Wake-Start<b>{Math.round(Number(apply.wake?.start_volume || 0) * 100)} %</b></span><span>Wake-Debounce<b>{apply.wake?.debounce_s ?? "—"} s</b></span></div></Card><Card><EmptyState icon={Icon.LockKeyhole} title="Nur lesbar" text="Apply-Delays, Sleep und Wake besitzen aktuell keine persistente Umbrella-Schreib-API. Deshalb zeigt die UX Werte an, speichert sie aber nicht doppelt im Frontend." /></Card></div>}
  </div>;
}
