import { createRoot } from "react-dom/client";
import { App } from "./App";
import "./demo.css";
import "./styles.css";
import type { Envelope, HassLike, MatrixData } from "./types";

const modules = { state: { available: true, healthy: true }, policy: { available: true, healthy: true }, apply: { available: true, healthy: true } };
const state = {
  context: "gaming", media_scenario: "gaming", subcontext: "gaming_grind", device: "ps5", gaming_source: "tv", gaming_platform: "ps5", entertainment_active: true, headset_active: false,
  active_reasons: ["scenario:gaming", "grind", "audio:homepods", "window:tilted"], context_cards: { bio_state: "awake", presence: "zuhause", household: "nicht_leer", transition: "none", activity: "free_time", day_state: "late_evening" },
  private_time_active: false, private_source: null, private_reason: null, private_blocked_reason: "auto_blocked:denon_off",
  classifiers: { ps5: { enum: 1, label: "gaming_grind", display_name: "Grind-Modus" }, pc: { enum: 0, label: "gaming_default" }, homepods: { enum: 0, label: "normal" } },
  now_playing: { device: "homepods", title: "Encore (Big Dreams)", artist: "Norma Jean Martine", volume: .3 },
  devices: { tv: { active: true, state: "on", source: "HDMI 2" }, apple_tv: { active: false, state: "off" }, ps5: { active: true, state: "playing", title: "Palworld" }, pc: { active: true, state: "on" }, homepods: { active: true, state: "playing", title: "Encore (Big Dreams)", artist: "Norma Jean Martine", volume: .3 }, denon: { active: true, state: "on", volume: .13 } }
};
const policy = {
  audio_owner: "gaming", audio_scenario: "gaming", audio_scenario_label: "PlayStation 5 aktiv", audio_scenario_detail: "Palworld", action: "keep_playing", volume_policy: "gaming_grind", is_grind: true,
  volume_target_homepods: .3, volume_target_denon: .13, subwoofer_allowed: false, volume_apply_allowed: true, reasons: [{ text: "Benni spielt gerade PlayStation 5.", severity: "ok" }, { text: "Grind-Modus ist aktiv.", severity: "ok" }, { text: "Musik läuft über die HomePods.", severity: "ok" }, { text: "Spielton wird leise über den Denon ausgegeben.", severity: "ok" }, { text: "Fenster ist gekippt, Lautstärke reduziert.", severity: "warn" }],
  volume_formula: { homepods: { base: .35, scenario_offset: 0, window_offset: -.05, activity_offset: 0, manual_nudge: 0, track_boost: 0, result: .3, plays: true }, denon: { base: .3, scenario_offset: -.12, window_offset: -.05, activity_offset: 0, manual_nudge: 0, track_boost: 0, result: .13, plays: true } },
  nudge: { manual_nudge: 0, min: -.3, max: .3, boost_active: false, boost_suppressed: false }
};
const apply = { apply_enabled: true, execute: true, ramp_active: false, ramp_step: 0, ramp_total: 16, debounce: { window_s: 5, pending: false, remaining_s: null }, plan: { homepods_action: "none", homepods_target: .3, denon_target: .13 }, gates: { apply_enabled: true, volume_apply_allowed: true, execute: true, stop_latch: false }, devices: { homepods: { configured: true, state: "playing", volume: .3 }, denon: { configured: true, state: "on", volume: .13 }, subwoofer: { configured: true, state: "off" } }, nachlauf: { active: false, pc_armed: false, tv_armed: false }, settings: { ramp_steps: 16, ramp_step_delay_s: 1, tiny_delta: .02, ducked_level: .1, debounce_seconds: 5, wake_start_volume: .1, wake_debounce_seconds: 5 }, sleep_tv: { delay_s: 2700, warn_lead_s: 60 }, wake: { start_volume: .1, debounce_s: 5 }, radio: { defaults: [{ name: "1LIVE", uri: "radiobrowser://1live" }, { name: "GAYFM", uri: "radiobrowser://gayfm" }, { name: "WDR 2", uri: "radiobrowser://wdr2" }, { name: "Radio 88.6", uri: "radiobrowser://886" }], ready: true }, log: [{ ts: new Date(Date.now() - 5000).toISOString(), action: "grind_mode", denon_target: .13, executed: true }, { ts: new Date(Date.now() - 9000).toISOString(), action: "window_offset", homepods_target: .3, denon_target: .13, executed: true }, { ts: new Date(Date.now() - 14000).toISOString(), action: "music_playing", homepods_target: .3, executed: true }] };
const matrix: MatrixData = { catalog: { dayphases: ["early_morning", "late_morning", "forenoon", "afternoon", "early_evening", "late_evening", "early_night", "late_night"], scenarios: ["off", "private", "gaming", "tv", "music"], scenario_labels: { music: "Musik", tv: "TV", gaming: "Gaming", private: "Privat", off: "Aus" }, activities: ["work_home", "work_away"], devices: ["homepods", "denon"] }, base: { homepods: { early_morning: .25, late_morning: .3, forenoon: .4, afternoon: .45, early_evening: .4, late_evening: .35, early_night: .3, late_night: .25 }, denon: { early_morning: .2, late_morning: .25, forenoon: .3, afternoon: .3, early_evening: .3, late_evening: .3, early_night: .25, late_night: .2 } }, scenario_off: { homepods: { music: 0, tv: 0, gaming: 0, off: 0 }, denon: { music: 0, tv: 0, gaming: 0, off: 0 } }, activity_off: { homepods: { idle: 0, free_time: 0, work_home: -.05, work_away: -.05, household: 0 }, denon: { idle: 0, free_time: 0, work_home: 0, work_away: 0, household: 0 } }, scalars: { opening_offset_homepods: -.05, opening_offset_denon: -.05, grind_homepods_offset: 0, grind_denon_offset: -.12, homepods_max: .65, denon_max: .55, private_denon_cap: .15, boost_offset: .15, active_min: .05, ducked_target: .15 }, override: { base: { homepods: { late_evening: .35 }, denon: {} }, scenario_off: { homepods: {}, denon: {} }, activity_off: { homepods: {}, denon: {} } } };
const envelope = <T,>(data: T): Envelope<T> => ({ contract: "benni_media.v1", ok: true, updated_at: new Date().toISOString(), stale: false, errors: [], warnings: [], modules, data });
const responses: Record<string, any> = { "benni_media/get_state": envelope(state), "benni_media/get_policy": envelope(policy), "benni_media/get_apply": envelope(apply), "benni_media/get_diagnostics": envelope({ bindings: { state: [{ key: "ps5_player", entity_id: "media_player.living_ps5", state: "playing", status: "bound" }], policy: [{ key: "opening", entity_id: "sensor.benni_master_opening", state: "gekippt", status: "bound" }], apply: [{ key: "denon", entity_id: "media_player.living_denon", state: "on", status: "bound" }] }, issues: [], raw: { state, policy, apply } }), "benni_media_policy/get_matrix": matrix };
responses["benni_media/get_overview"] = envelope({ scenario: "gaming", subcontext: "gaming_grind", device: "ps5", overview_device: "ps5", gaming_source: "tv", gaming_platform: "ps5", audio_owner: "gaming", audio_scenario_label: "PlayStation 5 aktiv", overview_audio_scenario_label: "PlayStation 5 aktiv", overview_audio_scenario_detail: "Palworld", volume_policy: "gaming_grind", apply_enabled: true, execute: true, entertainment_active: true, now_playing: state.now_playing, devices: state.devices, active_reasons: state.active_reasons, targets: { homepods_volume: .3, denon_volume: .13, subwoofer_allowed: false }, raw: { state, policy, apply } });
const hass: HassLike = { async callWS(message) { const type = String(message.type); if (type === "benni_media/action") return { ok: true, result: message.action === "search_radio" ? { results: [] } : {} }; if (type.includes("set_matrix") || type.includes("set_scalars") || type.includes("reset_matrix")) return matrix; await new Promise((resolve) => setTimeout(resolve, 40)); if (!responses[type]) throw new Error(`Demo kennt ${type} nicht`); return structuredClone(responses[type]); } };
createRoot(document.getElementById("demo")!).render(<><div className="demo-notice">Lokale Contract-Vorschau · keine Live-Konfiguration</div><App hass={hass} /></>);
